### ISSUE TITLE
git bclean reports an error if there are no branches to remove

### ISSUE THREAD

**Issue by fnf-peter-lacomb** [haacked/dotfiles#7]
Update the final command to `xargs -r git branch -d`  (passing `-r` to xargs so as not to run the command if the input is empty) to resolve.

On windows anyway - ymmv

**Comment by fnf-peter-lacomb** [comment]
BTW - Been using these aliases for nearly 10 years now. Thanks for sharing.

**Comment by haacked** [comment]
> Update the final command to `xargs -r git branch -d` (passing `-r` to xargs so as not to run the command if the input is empty) to resolve.

Want to submit a PR for that? You can do it through the browser by [going here](https://github.com/haacked/dotfiles/blob/main/git/gitconfig.aliases.symlink) and clicking the edit button (pencil icon).

> BTW - Been using these aliases for nearly 10 years now. Thanks for sharing.

:sparkles:

**Comment by haacked** [comment]
Ok, at some point I applied the suggestion myself. Thanks!

**Comment by haacked** [comment]
Correction: Issue creator did submit a PR and I merged it and never closed this issue.
